from typing import Protocol

from app.domain.models import ProfileStore, UserProfile


class ProfileRepository(Protocol):
    async def get_store(self) -> ProfileStore: ...

    async def get_active(self) -> UserProfile | None: ...

    async def create(self, profile: UserProfile) -> UserProfile: ...

    async def update(self, profile_id: str, fields: dict) -> UserProfile: ...

    async def delete(self, profile_id: str) -> None: ...

    async def activate(self, profile_id: str) -> UserProfile: ...
